/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    CrashTest: typeof import('./src/components/CrashTest.vue')['default']
    CrashTest2: typeof import('./src/components/CrashTest2.vue')['default']
    DisplayPeople: typeof import('./src/components/DisplayPeople.vue')['default']
    Filter: typeof import('./src/components/Filter.vue')['default']
    Gpt: typeof import('./src/components/Graph.vue')['default']
    Graph: typeof import('./src/components/Graph.vue')['default']
    OneFrameInformation: typeof import('./src/components/OneFrameInformation.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    Test: typeof import('./src/components/CrashTest2.vue')['default']
  }
}
