/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    CompareFrame: typeof import('./src/components/CompareFrame.vue')['default']
    copy: typeof import('./src/components/TopBars/TopBarTrackingChain.vue')['default']
    CrashTest: typeof import('./src/components/CrashTest.vue')['default']
    CrashTest2: typeof import('./src/components/CrashTest2.vue')['default']
    DisplayPeople: typeof import('./src/components/DisplayPeople.vue')['default']
    EditMetrics: typeof import('./src/components/EditMetrics.vue')['default']
    EditOneMetric: typeof import('./src/components/EditMetrics.vue')['default']
    EditPageTopBar: typeof import('./src/components/TopBars/EditPageTopBar.vue')['default']
    Filter: typeof import('./src/components/Filter.vue')['default']
    Gpt: typeof import('./src/components/Graph.vue')['default']
    Graph: typeof import('./src/components/Graph.vue')['default']
    OneFrameInformation: typeof import('./src/components/OneFrameInformation.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    ShowImage: typeof import('./src/components/ShowImage.vue')['default']
    Snackbar: typeof import('./src/components/Snackbar.vue')['default']
    Test: typeof import('./src/components/CrashTest2.vue')['default']
    TopBar: typeof import('./src/components/TopBars/TopBar.vue')['default']
    TopBarEditPage: typeof import('./src/components/TopBars/TopBarEditPage.vue')['default']
    TopBarTrackingChain: typeof import('./src/components/TopBars/TopBarTrackingChain.vue')['default']
    TrackingChainTopBar: typeof import('./src/components/TopBars/TrackingChainTopBar.vue')['default']
  }
}
